# EverMemOS System Configuration

name: "evermemos"
version: "1.0"
description: "EverMemOS"

adapter: "evermemos"

# LLM configuration
llm:
  provider: "openai"
  model: "deepseek-v3.2" #Qwen/Qwen2.5-7B-Instruct-AWQ"
  api_key: "sk-f653945d68514f5aa5e7f6ddc7bc04fb"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  # base_url: "${LLM_BASE_URL:http://192.168.111.4:8899/v1}"
  max_tokens: 32768

search:
  mode: "agentic"  # agentic | lightweight
  # When mode="lightweight", the search method defaults to "bm25_only".
  # Uncomment and set the following to override:
  # lightweight_search_mode: "hybrid"   # BM25 + Embedding + RRF fusion
  # lightweight_search_mode: "emb_only" # Only Embedding search

